const config = {
    botName: 'Bera',
    prefix: '.',
    owner: process.env.OWNER_NUMBER || '254717459770',
    ownerNumber: process.env.OWNER_NUMBER || '254717459770',
    nickApiEndpoint: process.env.NICK_API || 'https://apiskeith.top/ai/gpt41Nano',
    nickApiEndpointFallback: 'https://apiskeith.top/ai/gpt',
    nickApiKey: process.env.NICK_API_KEY || '',
    sessionDir: './session',
    dbPath: './Database/db.json',
    maxHistory: 20,
    readReceipts: true,
    publicMode: false,
    pterodactylUrl: process.env.PTERODACTYL_URL || '',
    pterodactylKey: process.env.PTERODACTYL_KEY || '',
    pterodactylAppKey: process.env.PTERODACTYL_APP_KEY || '',
    berahostApiKey: process.env.BERAHOST_API_KEY || 'bh_eb7b4bc1f92c2a2141d0379da8b1dba71b546c8f7d33b169',
    berahostApiUrl: process.env.BERAHOST_API_URL || 'https://kingvon-bot-hosting.replit.app/api',
    botImage: process.env.BOT_IMAGE || './assets/bera-ai-profile.png',
    version: '2.0.0',
    developer: 'Bera Tech',
    github: 'https://github.com/bera-tech-ai/bera-ai',
}

module.exports = config
